language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.5.5
  - DJANGO=1.6.2

install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt
  - pip install pep8
  - pip install -q -e .

script: python manage.py test
